<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Official SLSU Document</title>
  <style>
    body {
      font-family: DejaVu Sans, sans-serif;
      margin: 30px;
      font-size: 12pt;
    }

    .header {
      text-align: center;
      border-bottom: 3px solid #0047ab;
      padding-bottom: 10px;
      margin-bottom: 20px;
    }

    .header img {
      width: 80px;
      height: 80px;
    }

    .university-name {
      font-size: 16pt;
      font-weight: bold;
      color: #0047ab;
      margin: 5px 0;
    }

    .subtext {
      font-size: 10pt;
      color: #333;
    }

    h2.title {
      text-align: center;
      text-transform: uppercase;
      margin-top: 30px;
      color: #0047ab;
      font-weight: bold;
    }

    .content {
      margin-top: 10px;
      line-height: 1.6;
    }

    .signature-section {
      margin-top: 80px;
      display: flex;
      justify-content: space-between;
      width: 100%;
    }

    .signature-box {
      width: 45%;
      text-align: center;
    }

    .signature-line {
      border-top: 1px solid #000;
      margin-top: 60px;
      width: 80%;
      margin-left: auto;
      margin-right: auto;
    }

    .signature-label {
      font-size: 10pt;
      margin-top: 5px;
    }

    .footer {
      position: fixed;
      bottom: 0;
      left: 0;
      right: 0;
      text-align: center;
      font-size: 9pt;
      color: #777;
      border-top: 1px solid #ccc;
      padding-top: 5px;
    }

    .signature {
      margin-top: 80px;
      text-align: right;
    }

    .signature img {
      height: auto;
      width: 200px;
      /* ✅ makes it more visible */
      display: block;
      margin: 0 auto 10px auto;
    }
  </style>
</head>

<body>

  <div class="header">
    <img src="{{ public_path('images/slsu_logo.png') }}" alt="SLSU Logo">
    <div class="university-name">Southern Leyte State University</div>
    <div class="subtext">Sogod, Southern Leyte, Philippines</div>
    <div class="subtext">Tel. No. (053) 577-8299 | www.southernleytestateu.edu.ph</div>
  </div>

  <h2 class="title">Official Document</h2>

  <div class="content">
    <p><strong>Name:</strong> {{ $name }}</p>
    <p><strong>Email:</strong> {{ $email }}</p>
    <p><strong>Address:</strong> {{ $address }}</p>
    <p><strong>Notes / Purpose:</strong> {{ $notes }}</p>
  </div>

  <div class="signature-section">
    <div class="signature-box">
      <div class="signature-line"></div>
      <div class="signature-label">Authorized Official</div>
    </div>

    <div class="signature">
      <p>Signed electronically by:</p>
      @if(file_exists($signature))
        <img src="{{ $signature }}" alt="E-Signature">
      @endif

      <p><strong>{{ $signer }}</strong><br>Registrar, Southern Leyte State University</p>
    </div>


  </div>

  <div class="footer">
    Generated by the SLSU Digital Document System — {{ date('F d, Y') }}
  </div>

</body>

</html>
